### ISSUE TITLE
Connection Handling

### ISSUE THREAD

**Issue by KristinaTaylor** [PTC-ALM/TortoiseSI#10]
When the user first starts Windows, the client is typically not running. 

When Windows first asks for status, the Integrity client will be automatically launched.

When Windows asks for status on a file, a connection will be required, and the Integrity client will attempt a connection, using the method defined by the client preferences (prompt or no prompt).

If the client fails to connect, the integration will go into a "silent" offline mode.  To go online, a user must either explicitly connect via the Integrity Client, or do an explicit gesture.

Periodic status (implicit) operations (following the pattern established by wf folders), the integration should check si servers for an active connection.

**Comment by KristinaTaylor** [comment]
We need to make sure we appropriately document the experience when a user is connected to multiple servers. That is, the user would need to do one of the following, before they can expect their statuses to be kept up to date:
- explicitly connect to each SI server that they care about (have sandboxes for)
- store connection preferences for each SI server
- launch a TortoiseSI "view sandbox" gesture from the relevant folders

**Comment by gisraeli** [comment]
1. start the machine with no client / no connection => go to a folder with a sandbox in explorer & open it so you see the sandbox files
   -- connect to server and you should see the correct icons in the folder on the files
   -- try both with prompting on a off
2. try number 1 but press cancel on the connection dialog => there should be no icons
   -- connected the client manually => via the gui or cli, wait a minute, go the folder and refresh, you should see the icons
3. when not connected try to get multiple connection dialogs (should not happen) => press F5 in multiple folders or in a folder in a file open dialog (that is looking at a sandbox)

**Comment by gisraeli** [comment]
Also see both of Kristina's comments

**Comment by KristinaTaylor** [comment]
From review session: Hitting F5 multiple times when offline appears to crash Explorer.

**Comment by bleskows** [comment]
Decided to just give this a try on my local environment and I can't reproduce it.
1. Start my environment, log in with a user just to see statuses (plus make the state machine kick in).
2. Disconnect active connection through the task bar.
3. Hit F5 multiple times in a folder with files that are under source control (have Integrity statuses).
Following the above, I have not been able to make explorer crash. Anyone see anything wrong with my steps that I might be missing?

**Comment by KristinaTaylor** [comment]
Maybe try it without the client running ahead of time?  And/or.. disconnect the client, then shut it down, then go hit F5 a few times or open a few windows.

**Comment by atusek** [comment]
Including email trail discussion around this issue:

---

From: Taylor, Kristina 
Sent: March-17-15 11:51 AM
To: Leskowsky, Blaise; Tusek, Andrej; Fleming, Gordon
Cc: Reid, Randall
Subject: RE: Need to talk to Gilad about this "workaround"

I think I’m ok with the fix being to remove the code, based on what I’m seeing below. 

CC’ing Randall for his awareness of the issue/resolution.

Thank you for doing this investigation. If we find evidence of a memory leak in the future, we can try to resolve some other way that doesn’t make it crash. 

Kristina

From: Leskowsky, Blaise 
Sent: March-17-15 11:26 AM
To: Tusek, Andrej; Fleming, Gordon; Taylor, Kristina
Subject: RE: Need to talk to Gilad about this "workaround"

Note that this is still not a reliable indicator of how much memory the executable is actually using, but it provides a reasonable approximation of it, that is it cannot prove the existence of a leak or not.

From: Leskowsky, Blaise 
Sent: Tuesday, March 17, 2015 11:23 AM
To: Tusek, Andrej; Fleming, Gordon; Taylor, Kristina
Subject: RE: Need to talk to Gilad about this "workaround"

Some observations using perfmon. Tested using a large data set, 1 member and 1000 adds, which all require calls to wf fileinfo. Blue line represents Private Bytes of explorer process; pinkish line, Virtual Bytes. In terms of memory leak, the private bytes behaviour is more important. Growth in private bytes could mean memory leak, but apparently it could also mean memory fragmentation, so we should take care in how we want to interpret this data.

Rough event time breakdowns:
1.  10:52:35 – 10:54:55 – Start up explorer but don’t  navigate to sandbox with large data set yet. Private bytes around 48.5 MB. Make sure disconnected (offline), navigate to sandbox directory and keep hitting F5. Event viewer shows some status timeout warnings at this time.
2.  10:54:55 – 10:56:05 – do nothing in explorer
3.  10:56:05 – 10:58:25 – keep hitting F5
4.  10:58:25 – onwards – connect (online) and refresh a few times. Statues now show up. Hitting F5 after this time, see no significant increase in memory usage. 

![memorytest](https://cloud.githubusercontent.com/assets/6186615/6731060/439ee7e6-ce18-11e4-8fbe-8ca1aaac47ef.jpg)

From: Tusek, Andrej 
Sent: Tuesday, March 17, 2015 9:31 AM
To: Fleming, Gordon; Leskowsky, Blaise; Taylor, Kristina
Subject: RE: Need to talk to Gilad about this "workaround"

Agreed – we didn’t seen any evidence of memory leaks when this code was removed.

Blaise – you mentioned that you were seeing crashes yesterday. Are you able to do some testing with the code removed?

From: Fleming, Gordon 
Sent: March-17-15 9:17 AM
To: Leskowsky, Blaise; Taylor, Kristina
Cc: Tusek, Andrej
Subject: RE: Need to talk to Gilad about this "workaround"

I don’t think it is an issue based on our previous observations.  This method is called many times and when we lower the timeout to 1 second to force timeouts we are not seeing any increased memory usage by Windows explorer or any lingering network connections (which could be an indication that the smart pointer is never being freed).

According to the comment, it looks like Gilad was worried that that unique_ptr (smart pointer) would not be instantiated because it is being passed as a template parameter, i.e.  there is no guarantee that the std::async implementation instantiates this object before the timeout occurs.  From my perspective, the smart pointer is either instantiated or it is not and in either case we are fine.  If it is not instantiated then there is nothing to free and if it is instantiated then the smart pointer will free the IntegrityResponse object when it goes out of scope.

Gordon

From: Leskowsky, Blaise 
Sent: March-16-15 4:17 PM
To: Taylor, Kristina
Cc: Tusek, Andrej; Fleming, Gordon
Subject: RE: Need to talk to Gilad about this "workaround"

That seems to be consistent with what we thought as well.
I’m trying to think how we could prove it formally. It’s tricky to do on a real install since we make the timeout quite large (10 s). We know we can almost force timeouts by bumping that value down to 1 second in our dev environments, although I don’t remember if this works in both online and prompting states. At that point, not sure what we would do. Thoughts, Andrej and Gordon?

Blaise 

From: Taylor, Kristina 
Sent: Monday, March 16, 2015 4:09 PM
To: Leskowsky, Blaise
Cc: Tusek, Andrej; Fleming, Gordon
Subject: RE: Need to talk to Gilad about this "workaround"

Ok, so just based on my quick and dirty interpretation of the question, Gilad’s immediate response was:
i think I was worried about memory leaking. if they can make a dummy program that proves that there is no leak (a little bit tricky to do so, requires the right timing) then it would not be needed. make sure the test forces a time out. and make sure the constructor still gets called in that case… err that should say destructor not constructor.

I’ll send him the more detailed explanation, just to confirm.

From: Leskowsky, Blaise 
Sent: March-16-15 3:59 PM
To: Taylor, Kristina
Cc: Tusek, Andrej; Fleming, Gordon
Subject: Need to talk to Gilad about this "workaround"

Hello Kristina,

So the offending code is in fileInfo() in IntegrityActions.cpp. I have marked where we have seen the Explorer crash occur.
The problem is with the get() call status timeout handling: this leads to a memory access violation which puts us in the <future> library. We’re not quite sure the reasoning behind why responseFuture.get() specifically needs to be called here since according to the comment, it seems it’s a workaround for some issue we’re not sure of. We think that this call might ensure that the smart pointer will eventually get freed by making sure that references from both threads are decremented in the reference count for responseFuture , but we’re still not sure why we need to call responseFuture.get() when we know the response is not ready and it will lead to a memory access violation.

So far we have not observed any memory leaks occurring on fileinfo calls, and any open connections to the integration point eventually expire and close if they do timeout. Could Gilad provide his insight into what the exact purpose of that call is and what scenarios it should avoid?

IntegrityCommand command(L"wf", L"fileinfo");
                command.addSelection(file);

```
            std::future<std::unique_ptr<IntegrityResponse>> responseFuture =
                            std::async(std::launch::async, [command, &session]() { return session.execute(command); });

            std::future_status status = responseFuture.wait_for(std::chrono::seconds(10));
            if (status != std::future_status::ready) {
                            EventLog::writeWarning(L"get status timeout for " + file);

                            // need to call get so that the unique_ptr will exisit somewhere and go out of 
                            // scope and delete the command runner / response
                            std::async(std::launch::async, [&]{ 
                                                            std::unique_ptr<IntegrityResponse> response = responseFuture.get(); 
                                            }); // Windows explorer will crash here

                            return (FileStatusFlags)FileStatus::TimeoutError;
            }

            // TODO check future's exception... ?
            std::unique_ptr<IntegrityResponse> response = responseFuture.get();
            if (response == NULL) {
                            EventLog::writeWarning(L"get status failed to return response");
                            return NO_STATUS;
            }
```

Gordon and Andrej, feel free to jump in and correct anything incorrect I may have said here regarding the nature of the problem.

Thanks,

Blaise

**Comment by sharonzhao** [comment]
Using build 1.0.112.0, executed the online / offline test cases in section 6 (1032086) of TortoiseSI test suite (1012724).

**Comment by KristinaTaylor** [comment]
This has been demonstrated several times - closing now that it's been verified. There are other connection handling changes that are coming in issue #95, but this is done, for now.

**Comment by bleskows** [comment]
Removed needs docs: documented in Alpha release User Guide
