### ISSUE TITLE
Add initial draft of user guide

### ISSUE THREAD

**Issue by KristinaTaylor** [PTC-ALM/TortoiseSI#110]

**Comment by kevinpwatson** [comment]
The plan is to remove everything in the "doc" folder (old TortoiseGit docs), and replace it with a single HTML doc page for TortoiseSI.  There will also be an "images" and "css" folder to go along with the HTML page.

We should think about how to structure the doc folder so others could easily translate.  For translation, the HTML page and a couple images that display language would need to be translated.  The css could be shared with all translations.

A couple ideas:
1. Have an "index_XX.html" page for each translation directly under the "doc" folder, where the XX would be a language identifier (English would be: index_en.html, Japanese would be: index_ja.html).
   Usually the main HTML page of a site is named "index.html", but I don't think appending a language identifier would be a big deal since I doubt the doc page would be used as a main HTML page for a site.  We may even not want to use "index.html" and go with something like "tortoisesi_doc.html".
   This structure would allow the HTML pages to share the css folder and any images that don't require translation.  Also, those files would be easy to update in just one location.
   For images that require translation, we could either have language subfolders under the "images" folder, or append language identifiers to the end of images (TortoiseSIContextMenu_ja.png) and keep them all in the "images" folder.
2. Have a separate folder for each translation ("en" for English, "ja" for Japanese, etc.).
   Each folder would have its own "index.html", "images" and "css" subfolder.  This keeps things a bit cleaner, but images and the stylesheet would be duplicated for each language.  A change to the css or images would need to be updated for each language.  Or maybe we want to allow for different styles and images for each language?

**Comment by KristinaTaylor** [comment]
I like the first approach - I think it's simpler and lower maintenance, for now. If/when we decide we need separate images, we can always split those out in the future. I don't think we'd ever need different styles for different languages, but I can see how there may be a future benefit to different images (like screenshots, eventually).

**Comment by kevinpwatson** [comment]
@KristinaTaylor  @cwarnerPTC 

What should the name of the user doc be?

I've been thinking it should probably be something other than **index_en.html** in case there are other docs in the future.  It is currently checked in as **TortoiseSI for PTC Integrity User Guide - Alpha Release.html**.  That's a bit long and shouldn't really have spaces.

How about **TortoiseSIUserGuide_en.html**?

**Comment by KristinaTaylor** [comment]
I'm good with TortoiseSIUserGuide_en.html.

**Comment by KristinaTaylor** [comment]
User guide is now available at https://ptc-alm.github.io/TortoiseSI/docs/alpha/TortoiseSIUserGuide_en.html
