### ISSUE TITLE
Visual Studio Plugin

### ISSUE THREAD

**Issue by maschuru** [PTC-ALM/TortoiseSI#130]
Hi all,

I really like the approach of utilizing the tortoise "framework" to fill the gaps left in usability in Source Integrity.
Are there any plans to extend this idea to the Visual Studio Plugin?
The current implementation of the Visual Studio Integrity Plugin in a pain in the ***\* when it comes to managing solution shares.
A more "file and directory" centric approach might help a lot.

**Comment by KristinaTaylor** [comment]
We would like to apply this model to other integrations, yes. 

I see that you've contributed to the Integrity Jenkins integration in the past. Jenkins is the next one that we're currently looking at applying this development model to, since the current Jenkins integration is not actually supported by PTC directly. Visual Studio and Eclipse are others that the Integrity Product Management team has talked about "rebooting" using this approach.

I'm going to close this issue, since it's not directly tied to TortoiseSI, but if you'd like to continue this conversation, please feel free to reach out to me via the alm-oss@ptc.com email address.
