### ISSUE TITLE
Set up Builds

### ISSUE THREAD

**Issue by KristinaTaylor** [PTC-ALM/TortoiseSI#4]
Integrate with AppVeyor - make sure we have builds with build numbers that increment.

**Comment by bleskows** [comment]
AppVeyor build configuration (and more) documentation for reference: http://www.appveyor.com/docs/build-configuration

**Comment by bleskows** [comment]
How do we want the version format? Examples of things that could be done are 1.0.{build}-{branch}
which would give something like 1.0.123-master assuming we built the master branch.

**Comment by KristinaTaylor** [comment]
I like 1.0.{build}-{branch}

**Comment by gisraeli** [comment]
build is broken: Error parsing appveyor.yml: (Lin: 17, Col: 6, Chr: 463) - (Lin: 18, Col: 0, Chr: 470): While scanning a plain scalar, find a tab character that violate intendation.

**Comment by bleskows** [comment]
Currently we can get Win32 to build using AppVeyor's "unstable" os configuration which has Visual Studio 2013 CE and the correct ATL version. Previous versions of VS did not bundle this and WinDDK had too old a version of ATL. This os configuration is marked as unstable since the VM is very new (added by AppVeyor about 2 weeks ago). It should become stable soon, so we will need to monitor when that happens.

Next steps: the 64 bit version depends on files from the 32 bit version. Will have to figure out a way to access these in the 64 bit build since jobs are started on new VMs. Potential option may be to download artifacts from the 32 bit build to the VM about to build the 64 bit version.

**Comment by sharonzhao** [comment]
Verified using build 1.0.8.0.:
- Automated builds are running on PTC-ALM credentials.
- Build numbers are of the correct format and incremented.

**Comment by sharonzhao** [comment]
Verified using build 1.0.8.0.
