### ISSUE TITLE
Investigate whether we should start from TortoiseGit Commit dialog code or roll our own

### ISSUE THREAD

**Issue by KristinaTaylor** [PTC-ALM/TortoiseSI#49]

**Comment by flemingg** [comment]
Is there someone that can translate this dialog for me?
![image](https://cloud.githubusercontent.com/assets/7550325/6353386/0a8ac73a-bc17-11e4-95a1-d05f1cc350bd.png)

**Comment by bleskows** [comment]
Unless someone remembers/ was taking notes from the grooming session we had a while back, Sharon would be our resident translator.

**Comment by bleskows** [comment]
You might also want to take a look at #30. Kristina provided a mock-up here for a submit changes dialog (incidentally from that grooming session I mentioned before), trying to keep in mind huawei's use case

**Comment by KristinaTaylor** [comment]
@sharonzhao: any chance you could provide some translations for the content in this dialog? I know we reviewed in in one of our sessions, but we didn't write it down anywhere.

**Comment by sharonzhao** [comment]
See below the translation:

Submit Code
The Path of the Code: D:\Sandbox\MKS,                                                                                  Browse
Current Project: 
Filter File: .txt, .null, .c, .cpp, .h, .ini, .bat, .properties, .xml, .java, .css, .js, .cs, .py, .vcproj, .inc,  Filter

Display non-versioned file
                                        File Type,                            Scan Type,                                Modified or Not

Remark
Recent Remark
[reviewer]:
[review time]:

List of Related Issues
Current Version  
Defects,             Development Tasks
Title/Number,                                           Assigned User,                                                            Inquiry
                     Number,                       Title,                                    Assigned User,                Type  
How to use the Submit Code dialog,                                                                         Submit,      Cancel

**Comment by flemingg** [comment]
Recommendations:
-Re-use TortoiseGitProc framework for launching custom dialogs (e.g. commit dialog).  This framework can be used anywhere we need to display a custom dialog that Integrity does not already have.  
-Re-use the language framework for loading stand-alone language resource DLLs

Commit Dialog Re-Use:
The commit dialog makes use of a resizeable dialog library.  We can re-use this library for our custom commit dialog for the layout management and size management.  

Of course, most of the controls on the commit dialog cannot be re-used since their functionality is different than that which we need to implement for TortoiseSI and the controls and layout we need are different. 

We can re-use some elements of the custom file list control (CGitStatusListCtrl) that the TortoiseGit commit dialog uses. Further investigation required.

**Comment by KristinaTaylor** [comment]
The question has been answered, and the work to implement the recommendations above will be posted as separate issues.
