### ISSUE TITLE
Remove Wix custom UI

### ISSUE THREAD

**Issue by gisraeli** [PTC-ALM/TortoiseSI#57]
Investigate whether WixUI_Simplest.wxs is being used in either the TortoiseSI installer or the language pack installers, and if not, drop the file.  Blaise has already done further investigation into the other files in this area, and this looks like the only one that is unnecessary.

**Comment by bleskows** [comment]
Notes on the current structure based on my brief investigation:
- TortoiseSI.wxs - condition checks, sequencing of dialogs. Includes:
  - FeaturesFragment.wxi - available features for user to select on install
  - StructureFragment.wxi - lots of registry and icon overlay stuff
  - UIFragment.wxi - define resources and provide actual dialog layout.
- WixUI_Simplest.wxs - not really sure what functionality this provides. Its a wix fragment of some kind, references a lot of the "static" images i.e. include/BannerStatic.jpg. I couldn't find anything in the project that includes it, so maybe we remove that and make sure installer for TortoiseSI and the langauge packs don't use it.

The current TortoiseSI.wxs structure of includes seems to make sense, since it splits things into meaningful fragments. Recommend we keep that as-is.

**Comment by bleskows** [comment]
More investigation, I think the WixUI_Simplest.wxs was used for localizing extensions since it references a lot of loc variables. I suspect this must be a remnant of TortoiseSVN stuff since loc variables are normally defined in .wxl files which neither we nor TortoiseGit have in the solution. In fact, TortoiseGit has never done much work with this file from the commit history. In which case, I'll probably drop this file as originally planned and make sure I don't break anything in the installers.

**Comment by bleskows** [comment]
Can be verified using build [1.0.93.0](https://ci.appveyor.com/project/PTC-ALM/tortoisesi/build/1.0.93.0). Not sure what sort of verification should be required for this, maybe sanity pass to make sure I didn't break the TortoiseSI installer.
