### ISSUE TITLE
Add Move and Rename operations for controlled files

### ISSUE THREAD

**Issue by KristinaTaylor** [PTC-ALM/TortoiseSI#83]
Using the rename and move operations that are built into Windows will ultimately end up with Integrity recognizing the file as having been dropped and re-added. As a result, the integration needs to expose the Integrity Move and Rename actions. These commands both need to have the options set appropriately so that the working file gets moved or renamed correctly as part of the action.

Like add (see #18), move should follow the client preferences for the createSubprojects option.

**Comment by bleskows** [comment]
Had this discussion with @KristinaTaylor and @atusek but it was observed that if the gesture verb is "Rename", the shell will make a call to the WinAPI rename and not even go through our code. TortoiseGit avoided this problem because their gesture is "Rename...". Should we follow this pattern?
Note, for consistency this would also mean we would change other resource strings. @KristinaTaylor, should we do this across the board or just limit it to member/non-member-based ops (keep view strings as-is)? I feel the latter case is the reasonable option here.

**Comment by KristinaTaylor** [comment]
I agree. Add the "..." to the file-based operations: anything that will pop up a dialog before proceeding with an action.

**Comment by bleskows** [comment]
Based on the above, strings for the following ops will be affected: 
- Add 
- Check Out
- Check In
- Drop
- Lock
- Revert
- Move
- Rename

**Comment by KristinaTaylor** [comment]
:+1:

**Comment by bleskows** [comment]
Can be verified with build [1.0.105.0](https://ci.appveyor.com/project/PTC-ALM/tortoisesi/build/1.0.105.0) or later

**Comment by sharonzhao** [comment]
The testing of Move and Rename file-based operations has been covered by the testing of issue #18 using build 1.0.112.0.

This issue can be closed.

**Comment by KristinaTaylor** [comment]
Reviewed in Sprint 8 & 9 reviews. Closing.

**Comment by bleskows** [comment]
Removed needs docs: documented in Alpha release User Guide
