### ISSUE TITLE
Check out and Lock gestures should be using :working instead of the default :member

### ISSUE THREAD

**Issue by KristinaTaylor** [PTC-ALM/TortoiseSI#84]

**Comment by bleskows** [comment]
For lock I can see this making sense, since the LockDialog assumes that we are locking :member. Now for checkout, passing --revision=:working as an option just means we set the value in Pre-Defined Revision to "Working" as opposed to "Member". Given that this can be changed in the checkout dialog by the user anyway, is the intent here to default a TortoiseSI checkout to :working since the user is expecting to checkout whatever revision happens to be in their sandbox?

**Comment by KristinaTaylor** [comment]
These both should be defaulting to :working. The user is, as you say, expecting to work with whatever happens to be in their sandbox.

**Comment by bleskows** [comment]
Can be verified using build [1.0.99.0](https://ci.appveyor.com/project/PTC-ALM/tortoisesi/build/1.0.99.0) or later.

**Comment by sharonzhao** [comment]
Lock and Checkout gesture uses --revision=:working. Verified with build 1.0.112.0.

This issue can be closed.

**Comment by KristinaTaylor** [comment]
reviewed in sprint 8 review - closing

**Comment by bleskows** [comment]
Removed needs docs: documented in Alpha release User Guide
